### PR TITLE
Initial draft

### PR DESCRIPTION
**Pull request by sghung**
The initial draft of the Nexus repo integration with Appsody. The code files are relative to the README, so all those files need to be uploaded to the guide.

### CODE REVIEW

**Comment by alohr51** [comment]
@sghung Guides aren't necessarily full projects like this. I would imagine this code would live elsewhere such as your GitHub or somewhere else and your guide could reference that.

These guides are usually all written and have _some_ code involved, but not this much. I would take a look at some of the existing guides, they will help show you what a guide normally entails https://kabanero.io/guides/

**Comment by alohr51** [comment]
On second thought it might okay to have it all here, do you expect the readers to clone this repo and use that code in the code dir? Usually the smaller the code the better for maintainability purposes.

**Comment by sghung** [comment]
Thanks for reviewing @alohr51. A lot of code needs to be modified for the nexus repository support. The user can clone everything if they want, but it won't be a working project out of the box. It is just for reference. I didn't want the guide to have full code snippets for every file, since that makes the guide much too long.

I originally had this in my own github ID, but I wanted it to be more official (and who knows if something ever happens to my own ID), so I decided to put it here instead.

**Comment by sghung** [comment]
@ralanlittle @nateziemann can you please review? I have tested the changes locally. One thing I'd like to do, is to link the files to github directly. That is, instead of `link:code/my-java-microprofile/image/project/install-dev-deps.sh[install-dev-deps.sh]` we use `link:https://github.com/kabanero-io/draft-guide-nexus-repository-integration-with-appsody/blob/master/my-java-microprofile/image/project/install-dev-deps.sh[install-dev-deps.sh]. However, I can't use that link style yet since the code isn't in the repo yet (it will get in from this PR. Also, I don't want to have "draft-guide" as the repo name.

We might have to change these links post publish, otherwise viewing the files isn't too great. The linked files have too many lines to display in the post.

**Comment by nateziemann** [comment]
@sghung a few key observations and  requested  changes:

1. Title:  The materials for Kabanero.io should be centered  on usage of Kabanero and/or directly relate to usage of the product we sell as Cloud Pak for Applications.  The intent of the guide should  be how to use  a nexus repository.   Just remove the words "with Appsody" from the title.  We want to focus on enabling the product to use a nexus repo, not lead with which open technology you actually must tweak to do that.  

2.  Messaging:  Kabanero and ICPA have features called "Application Stacks".  This is a noun, an asset, without exposing it's underlying technology.  Today they are implemented using an open technology from Appsody.dev.  I want everyone to stop prepending different assets like stacks, pipelines, templates, etc  w/ the "brand name of the open technology that delivers it", meaning Appsody or Kabanero or ICPA.

So I'd  like this guide  to replace "Appsody Stacks" with  "Application Stacks".  It doesn't change the technical work  or fact that you customize stacks using contructs, CLI, etc sourced  from Appsody itself. 

example:  "Create a new Appsody Maven stack by running _appsody stack create my-java-microprofile --copy incubator/java-microprofile_ on your operating system terminal"   

becomes:  "Create a new Application  Stack by running _appsody stack create my-java-microprofile --copy incubator/java-microprofile_ on your operating system terminal"

3.  In  Kabanero (and ICPA), the act of creation and customization of Application Stacks for their Enterprise, is a Champ persona workflow.  One that is done using a Local Hub which then they  expose to the developers.  I want to ensure this guide is written for and targeted for them.   I have not read this whole document, so this is a comment, the  guide could already do this, but I wanted to share my PoV on the  intent.  If  parts of doc feel, too centric to a developer doing this themselves, I want that changed for  the Kabanero.io hosted guide.

**Comment by nateziemann** [comment]
@stephenkinder this document and  my  feedback below has direct relation to  what  we're building for the tech sellers at  Fast  Start.  You may want to  read  the  draft guide  readme and my expectations on changes above.  Could be a good "real world" customization use case for "backup section" of our materials??

**Review by nateziemann — CHANGES_REQUESTED** [review]
@sghung a few key observations and requested changes:

Title: The materials for Kabanero.io should be centered on usage of Kabanero and/or directly relate to usage of the product we sell as Cloud Pak for Applications. The intent of the guide should be how to use a nexus repository. Just remove the words "with Appsody" from the title. We want to focus on enabling the product to use a nexus repo, not lead with which open technology you actually must tweak to do that.

Messaging: Kabanero and ICPA have features called "Application Stacks". This is a noun, an asset, without exposing it's underlying technology. Today they are implemented using an open technology from Appsody.dev. I want everyone to stop prepending different assets like stacks, pipelines, templates, etc w/ the "brand name of the open technology that delivers it", meaning Appsody or Kabanero or ICPA.

So I'd like this guide to replace "Appsody Stacks" with "Application Stacks". It doesn't change the technical work or fact that you customize stacks using contructs, CLI, etc sourced from Appsody itself.

example: "Create a new Appsody Maven stack by running appsody stack create my-java-microprofile --copy incubator/java-microprofile on your operating system terminal"

becomes: "Create a new Application Stack by running appsody stack create my-java-microprofile --copy incubator/java-microprofile on your operating system terminal"

In Kabanero (and ICPA), the act of creation and customization of Application Stacks for their Enterprise, is a Champ persona workflow. One that is done using a Local Hub which then they expose to the developers. I want to ensure this guide is written for and targeted for them. I have not read this whole document, so this is a comment, the guide could already do this, but I wanted to share my PoV on the intent. If parts of doc feel, too centric to a developer doing this themselves, I want that changed for the Kabanero.io hosted guide.

**Comment by sghung** [comment]
Thanks @nateziemann for your review.

- Fixed the title and removed "with appsody". The repository name has to be renamed to remove "with appsody" as well as the permalink, but that can be done after when everyone approves
- I use "Application Stack". Changed that within the instructions and in the blurb at the top
- For doing development from Champ's perspective, here are my thoughts on it: in my original writeup I don't tell Champ to publish the stacks to dockerhub, instead do it locally. However, for the stacks to be picked up by codewind, they must be hosted externally somewhere. A file cannot be used (https://github.com/eclipse/codewind/issues/668). If Champ truly wanted to test the stack outside of codewind, they could, but then the user is just using appsody. I still believe testing the stack with codewind is better, since they can do development in the IDE and get the created stack working and then copy that code back into the stack's template. As a result, what I have right now is the minimal work Champ needs to do for testing their stack without needing to push the stacks to dockerhub. Having a better Champ experience in codewind is something I have opened issues for and is something I can bring up in prioritization meetings

**Comment by sghung** [comment]
@ralanlittle Alan, can you please review this guide? Thank you

**Review by nateziemann — APPROVED** [review]
I reviewed changes since last review, looks better.  Publish and if other clean-up is needed, we'll iterate.  Go for publish.

**Comment by deboer-tim** [comment]
Discussed with Nate, both of us are good to go and agree we should not hold up for Alan. Please remove his review and go ahead and publish.

**Review by alohr51 — APPROVED** [review]

**Review by nateziemann — COMMENTED** [review]
I approve.

**Pull request merged**
